### ISSUE TITLE
Dataset or quadgroup? 

### ISSUE THREAD

**Issue by cristianvasquez** [pietercolpaert/Wurtle.js#1]
Hi,

Nice idea about the pragmas! I was coincidentally doing something similar 

I noticed that the emitted groups are arrays of quads. Would it make sense to emit datasets instead, or is the current setup specifically to maintain the order of quads?

Cheers

**Comment by pietercolpaert** [comment]
The order of the quads are indeed of no importance. I think it would make sense to code against the [RDFJS Dataset Core interface](https://rdf.js.org/dataset-spec/#datasetcore-interface) instead of just using an array

**Comment by pietercolpaert** [comment]
Having given this more thought: I would like to just keep an Array of quads in this library as the output to allow a user of the library to load it into a Dataset implementation of choice.

Thanks for the suggestion though!
